[project]
name = "bu-robotics-club-arctos"
version = "0.1.0"
description = "BU Robotics Club - Custom Python control software for Arctos"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyserial>=3.5",
    "pytest>=9.0.2",
    "python-can",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["arctos"]

[tool.pytest.ini_options]
testpaths = ["tests"]
